project:
  type: website 
  output-dir: docs
  
website:
  title: "Jenny Shen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Jenny-Shen-Resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



